### ISSUE TITLE
Can't compile whit ESP8266

### ISSUE THREAD

**Issue by bcampetelli** [frankjoshua/rosserial_arduino_lib#1]
wen i commpile the HelloWorld of ESP8266, whit the ESP8266 core selected, the compiler drop this response:

Arduino:1.8.2 (Windows 10), Tarjeta:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Opciones de compilación cambiadas, reconstruyendo todo
In file included from C:\Users\Bruno\Documents\Arduino\libraries\Rosserial\examples\Esp8266\HelloWorld\HelloWorld.ino:12:0:

C:\Users\Bruno\Documents\Arduino\libraries\Rosserial\src/ros.h:40:26: fatal error: avr/pgmspace.h: No such file or directory

 #include <avr/pgmspace.h>

                          ^

compilation terminated.

exit status 1
Error compilando para la tarjeta NodeMCU 1.0 (ESP-12E Module).

Este reporte podría tener más información con
"Mostrar salida detallada durante la compilación"
opción habilitada en Archivo -> Preferencias.

**Comment by ShaunPrice** [comment]
In the library file library.properties change the line  below:
    architectures=**avr**
to:
    architectures=*****

It's currently targeting only AVR micro-controllers but looks to work with many others.

**Comment by frankjoshua** [comment]
Done.
