### ISSUE TITLE
Subscriber failed - BLINK example

### ISSUE THREAD

**Issue by rjam92** [frankjoshua/rosserial_arduino_lib#12]
Using an Arduino MEGA 2560 and running the blink example following the rosserial turtorials I end up with the following error:
Creation of subscriber failed: unknown error handler name 'rosmsg'

Ros msg works perfectly on the Linux system. I am using Ubuntu 18.04 and ros melodic

**Comment by frankjoshua** [comment]
Better to ask questions on https://answers.ros.org/questions/
