### ISSUE TITLE
#include<cstring> and std::memcpy in ros/msg.h are causing Arduino IDE compiler errors

### ISSUE THREAD

**Issue by TCIII** [frankjoshua/rosserial_arduino_lib#18]
@frankjoshua,

 Why haven't the following corrections to ros/msg.h been made in the latest version of rosserial_arduino_lib:

Summary: (Changes) File - ros/msg.h

Change -> #include <cstring> to #include <string.h> in line 40
Change -> std::memcpy() to memcpy() in lines 68 and 182

Making these changes prevents Arduino IDE complier errors in Arduino ino programs that incorporate commands from the rosserial_arduino_lib.

Regards,
TCIII

**Comment by Mubashir-alam** [comment]
it works

**Comment by frankjoshua** [comment]
OK. It's merged now. Sorry for the delay.
